### PR TITLE
fix(wavm) use PRIu64 for printf portability across architectures

### LINKED ISSUE #653: Wrong format for debugging on 64 bit platform
https://github.com/Kong/ngx_wasm_module/commit/73aaff4ba06e2648fa946c722c0849dd3a88ea7a#commitcomment-150327118

### PR DESCRIPTION
**Pull request by dev-null-undefined**
Fixes #653

### CODE REVIEW

**Comment by thibaultcha** [comment]
Can we just use %lu and avoid anything too fancy? We strive for consistency and simplicity.

**Comment by dev-null-undefined** [comment]
That would work only on 64bit platform and break on 32bit, which for debug printing is probably ok-ish, but I do not think that this is too complex for the benefit of being portable, ofc the call is yours.

**Comment by thibaultcha** [comment]
It does seem like we require C99 already anyway so it should be good. To merge it we will need you to sign the CLA though.

**Comment by thibaultcha** [comment]
Thank you!

**Pull request merged**
